repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: "Ruff Lint"
        language: system
        files: ^.*\.py$
        entry: "./scripts/lint"
        require_serial: true
      - id: ruff-format
        name: "Ruff Format"
        language: system
        files: ^.*\.py$
        entry: "./scripts/format"
        require_serial: true
